spring:
  mail:
    host: smtp.gmail.com
    username: user@mail.com
    password: password
    properties: 
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
support:
  email:
    from: wleylop22@gmail.com